import { RoleConfig } from '../config/types';

export const roleConfig: RoleConfig = {
  5: ['villager', 'villager', 'villager', 'werewolf', 'seer'],
  6: ['villager', 'villager', 'villager', 'villager', 'werewolf', 'seer'],
  7: [
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'seer',
    'madman',
  ],
  8: [
    'villager',
    'werewolf',
    'werewolf',
    'seer',
    'madman',
    'hunter',
    'freemason',
    'freemason',
  ],
  9: [
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'seer',
    'fox',
    'immoralist',
    'immoralist',
  ],
  10: [
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
  ],
  11: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
  ],
  12: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
    'fox',
  ],
  13: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
    'fox',
    'immoralist',
  ],
  14: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'seer',
    'medium',
    'hunter',
    'werewolf',
    'werewolf',
    'werewolf',
    'freemason',
    'freemason',
  ],
  15: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
    'freemason',
    'freemason',
    'fox',
    'immoralist',
  ],
  16: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
    'freemason',
    'freemason',
    'fox',
  ],
  17: [
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'villager',
    'werewolf',
    'werewolf',
    'werewolf',
    'seer',
    'medium',
    'madman',
    'hunter',
    'freemason',
    'freemason',
    'fox',
  ],
};

export const teammateMapping: Record<string, string> = {
  werewolf: 'werewolf',
  freemason: 'freemason',
  immoralist: 'fox',
  fanatic: 'werewolf',
};
